### PR TITLE
Fix CURRENT file newline error

### PR DESCRIPTION
**Pull request by gentlegiantJGC**
There were some cases of users hitting an error about not having a newline in the leveldb CURRENT file.
These changes should handle any number of trailing carriage return and newline characters (including none).
If the CURRENT file is empty a new error will be thrown instead to make it distinct from the newline error.

### CODE REVIEW

**Comment by dktapps** [comment]
under what circumstances is the CURRENT newline missing? ...

**Comment by gentlegiantJGC** [comment]
Sorry this was created for the wrong repository. Was supposed to be committed to the Amulet one.
We have had some users complaining of the error `Corruption: CURRENT file does not end with newline`
I am not quite sure what is causing this but the last commit should remove all trailing `\r` and `\n` characters.

**Comment by dktapps** [comment]
I think you should probably investigate those files. If the newline is missing, there's a good chance the file is actually corrupted.

**Comment by gentlegiantJGC** [comment]
This is a fair point.
The modified code allows there to be zero or more `\r` and `\n` characters at the end. This should handle all possible cases.
I am not saying this should be made part of the Mojang version but it should fix the issues Amulet has opening some worlds.

The code does check further down if the final string is an actual file so I don't think my modified code should break anything.
If the file is empty or just contains \r or \n characters the modified code will report it as empty and if it doesn't contain a valid file string that will get errored further down.

**Pull request closed without merging**
